import pandas as pd
import matplotlib.pyplot as plt

# Load data from CSV file
data = pd.read_csv('myfile.csv')

# Ensure the necessary columns are present
if 'A' not in data.columns or 'B' not in data.columns:
    raise ValueError("CSV file must contain columns 'A' and 'B'.")

# Create the bar chart
plt.figure(figsize=(10, 6))
plt.bar(data['A'], data['B'], color='skyblue')

# Add title and labels
plt.title("This is a bar chart generated by an LLM")
plt.xlabel('A')
plt.ylabel('B')

# Show the chart
plt.show()
